name: Qodana
on:
  pull_request:
  push:


jobs:
  Qodana:
    runs-on: ubuntu-latest
    if: github.repository == 'zim514/script.service.hue'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@latest
        with:
          args: --baseline,qodana.sarif.json
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
