name: Qodana
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  Qodana:
    runs-on: ubuntu-latest
    if: github.repository == 'zim514/script.service.hue'
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@latest
        with:
          use-caches: true
          cache-default-branch-only: true
          args: --baseline,qodana.sarif.json
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}